### ISSUE TITLE
Any thoughts on QUIC

### ISSUE THREAD

**Issue by lonnietc** [aburdulescu/ez#58]
Hello,

I have just installed your ez software for testing since I am working on a small P2P project and need a good P2P filesystem across all of the nodes.

I was just wondering if you considered the possibility of using the QUIC-Go library since QUIC is supposed to be MUCH faster than TCP transfers.

```
https://github.com/lucas-clemente/quic-go
```

Also for a question on the operation. Do I understand correctly in that to add more files stored on additional nodes then I need to put the EZ Seeder on each of them and point the EZ Tracker parameter to the main "EZT" tracker node?

```
Machine 1
(tracker)
>> ezt

(a seeder)
>> ezs -seedaddr 192.168.0.10 -trackeraddr 192.168.0.10

(add files on this node)
>> ezl add path_to_file

Machine 2
(a seeder)
ezs -seedaddr 192.168.0.11 -trackeraddr 192.168.0.10

(add files on this node)
>> ezl add path_to_file

Machine 3
(a seeder)
ezs -seedaddr 192.168.0.12 -trackeraddr 192.168.0.10

(add files on this node)
>> ezl add path_to_file

Client Node 1 (could also be on any of the Machine Nodes as well)

>> ez tracker 192.168.0.10
>> ez ls
>> ez get file_id

Client Node 2 (could also be on any of the Machine Nodes as well)

>> ez tracker 192.168.0.10
>> ez ls
>> ez get file_id
```

QUESTIONS:

1.) So then the client nodes will get the files from which ever node the "ez tracker" says has the file and then it will be a P2P transfer from the Machine node to the Client node (above example)?

2.) How does the "ezl add" or actually the "ezt" tracker handle the spread out directory that may have the same file located on different Machine nodes but added with "ezl" to that local storage. (i.e. If someone loads the same file on different nodes)?

3.) Would it be possible to have trackers on each node and then have them always update their databases to be consistent across each of them?

Thanks and looking forward to hearing from you.

**Comment by aburdulescu** [comment]
I'll start by first mentioning that this project is a learning exercise, it's not "real"/stable/production ready/quality software.
There are barely any automated tests, I tested it manually and mostly on the same machine using docker and docker compose, or any real tests on real hardware and real network setup.
There are also some known rough edges/bugs and I'm sure a lot more unknown :).

That being said, here's my answers:

> I was just wondering if you considered the possibility of using the QUIC-Go library since QUIC is supposed to be MUCH faster than TCP transfers.

I haven't considered using QUIC at the time when I was writing ez since I wasn't aware of it. 
But even if I know about it I don't think I would've used it since, afaik, QUIC is meant to replace TCP+TLS and I intentionally  set the precondition that this software is used in local networks only(meaning all nodes can talk with each other(no NAT traversal) and all nodes trust each other(no TLS) since it's a local network closed to the outside) thus avoiding the overhead added by making it open/available to/over the internet.

> Also for a question on the operation. Do I understand correctly in that to add more files stored on additional nodes then I need to put the EZ Seeder on each of them and point the EZ Tracker parameter to the main "EZT" tracker node?

Correct, ezs needs to know what is its public address(where the clients will connect and download file chunks) and the tracker address.

To clarify, the tracker is a central component and there is only one of it.
This is similar to initial design of BitTorrent protocol where there is a central tracker which keeps track of the list of available files and who has them.

> 1.) So then the client nodes will get the files from which ever node the "ez tracker" says has the file and then it will be a P2P transfer from the Machine node to the Client node (above example)?

The download of a file is two-step, first get the list of seeders that file from the tracker then start downloading in parallel chunks of that file(piece by piece).
A chunks is 8MB, a piece is 8KB and and at most 8 chunks are downloaded at a time to limit resource consumption.
After those 8 chunks are downloaded and checked against the checksum given by the peer(to make sure no error happened during transfer) they are written to disk.
This process keeps repeating until the whole file is downloaded and written to disk.

> 2.) How does the "ezl add" or actually the "ezt" tracker handle the spread out directory that may have the same file located on different Machine nodes but added with "ezl" to that local storage. (i.e. If someone loads the same file on different nodes)?
3.) Would it be possible to have trackers on each node and then have them always update their databases to be consistent across each of them?

`ezl add` only notifies `ezs` to add that file to its database.
When `ezs` receives that request, it first does some processing for that file(like breaking into chunks and calculating the chunks checksums and storing them for later use, see above) then sends a request to `ezt` to add this new file to its own database and then it also adds the file to a file watcher(fsnotify) to handle cases like file removal/rename etc.
There's also some other scenarios to consider.
When a seeder stops and starts again, at startup, it will send its list of files from its database to the tracker.
There's also the case when `ezt` might stop for some reason, this is also handled.
Each seeder also has a UDP multicast server called tracker probe server which will receive a multicast request from the tracker when the tracker starts up and the seeder will respond with its list of files.

As you may note from above, the tracker has no persistent state, its state is always rebuilt at startup and updated during its lifetime by the seeders.

**Comment by lonnietc** [comment]
Hello,

Thanks for the wonderful reply and I was able to test EZ across 2 Windows machines in which it worked pretty good.

I truly appreciate the explanation and clarification on my questions since it will be very helpful in going forward as I can learn a lot from EZ.

I was wondering the reason for the hardcoded address (239.23.23.0:22203) in the ezt main.go for the "sendProbeToSeeders:

```
https://github.com/aburdulescu/ez/blob/ff6b9a1d78980c6b412642a7ad17f6fd9fbb012d/cmd/ezt/main.go#L28
```

Also, do you plan to continue more development on EZ?

**Comment by aburdulescu** [comment]
> I was wondering the reason for the hardcoded address (239.23.23.0:22203) in the ezt main.go for the "sendProbeToSeeders:

No reason, it's a random address, it can be any other valid IP multicast group address.

> Also, do you plan to continue more development on EZ?

I don't have any plan for this project. It's a hobby project, so I may or may not work on it based on available time and interest.
